CREATE SCHEMA users;
CREATE SCHEMA courses;

CREATE TABLE users.roles(
	id SERIAL PRIMARY KEY UNIQUE NOT NULL,
	role VARCHAR UNIQUE NOT NULL
);

CREATE TABLE users.users(
	id SERIAL PRIMARY KEY UNIQUE NOT NULL,
	email VARCHAR UNIQUE NOT NULL,
	username VARCHAR(30) UNIQUE NOT NULL,
	password VARCHAR(128) NOT NULL,
	role_id INTEGER NOT NULL,
	FOREIGN KEY (role_id) REFERENCES users.roles(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE courses.courses(
	id SERIAL PRIMARY KEY UNIQUE NOT NULL,
	code VARCHAR UNIQUE NOT NULL,
	name VARCHAR NOT NULL,
	year INTEGER NOT NULL
);

CREATE TABLE courses.lessons(
	id SERIAL PRIMARY KEY UNIQUE NOT NULL,
	date DATE NOT NULL,
	course_id INTEGER NOT NULL,
	FOREIGN KEY (course_id) REFERENCES courses.courses(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE courses.notes(
	id SERIAL PRIMARY KEY UNIQUE NOT NULL,
	content TEXT NOT NULL,
	lesson_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(), 
	FOREIGN KEY (lesson_id) REFERENCES courses.lessons(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES users.users(id) ON UPDATE CASCADE ON DELETE CASCADE
);