CREATE TABLE roles(
	id SERIAL PRIMARY KEY UNIQUE NOT NULL,
	role VARCHAR UNIQUE NOT NULL
);

CREATE TABLE users(
	id SERIAL PRIMARY KEY UNIQUE NOT NULL,
	email VARCHAR UNIQUE NOT NULL,
	username VARCHAR(30) UNIQUE NOT NULL,
	password VARCHAR(128) NOT NULL,
	role_id INTEGER NOT NULL,
	FOREIGN KEY (role_id) REFERENCES roles(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE courses(
	code VARCHAR UNIQUE NOT NULL,
	name VARCHAR NOT NULL,
	professor VARCHAR NOT NULL
);

CREATE TABLE lessons(
	id SERIAL PRIMARY KEY UNIQUE NOT NULL,
	course_code VARCHAR NOT NULL,
	date DATE NOT NULL,
	start HOUR NOT NULL,
	end HOUR NOT NULL,
	classroom VARCHAR NOT NULL,
	FOREIGN KEY (course) REFERENCES courses(code) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE notes(
	id SERIAL PRIMARY KEY UNIQUE NOT NULL,
	lesson_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	content TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(), 
	FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);